#!/bin/bash
module load license/default
module load synopsys/vcs/2024.09-SP1
module load synopsys/syn/2024.09-SP2
module load synopsys/tmax/2022.12
module load cadence/innovus/19.11_000
module load synopsys/verdi/2024.09-SP1
module load synopsys/spyglass/2023.12-SP1
module load synopsys/zoix/2024.09-SP1
module load synopsys/primetime/2024.09-SP2

# Library compiler used for asap7 
module load synopsys/lc/2025.06-SP1
