#!/usr/bin/env python3
#
# NOTE: this ExampleDriver works for asap7 and nangate45. the custom hooks are
# only used for asap7 though.

import os

from hammer.vlsi import CLIDriver, HammerTool, HammerToolHookAction

from typing import Dict, Callable, Optional, List

def dont_touch_srams(x: HammerTool) -> bool:
    x.append("foreach_in_collection ram [get_references -hierarchical \"*tc_sram_wrapper*\"] {")
    x.append("set_attribute $ram is_memory_cell true")
    x.append("set_attribute $ram is_physical_black_box true" )
    x.append("set_dont_touch $ram")
    x.append("set_attribute $ram is_black_box true")
    x.append("}")

    x.append("foreach_in_collection ram [get_references -hierarchical \"*tc_sram_wrapper_cache_techno*\"] {")
    x.append("set_attribute $ram is_memory_cell true")
    x.append("set_attribute $ram is_physical_black_box true" )
    x.append("set_dont_touch $ram")
    x.append("set_attribute $ram is_black_box true")
    x.append("}")

    x.append("foreach_in_collection ram [get_references -hierarchical \"sram\"] {")
    x.append("set_attribute $ram is_memory_cell true")
    x.append("set_attribute $ram is_physical_black_box true" )
    x.append("set_dont_touch $ram")
    x.append("set_attribute $ram is_black_box true")
    x.append("}")

    return True

def insert_internal_memory_collar(x: HammerTool) -> bool:
    if x.get_setting("synthesis.dc.insert_dft.memory_wrapper"):
        x.append(x.insert_test_points(["sram", "ram_ext"]))
    return True

def insert_atpg_memory_collar(x: HammerTool) -> bool:
    x.additional_modules = [".*sram.*"]
    return True

class ExampleDriver(CLIDriver):
    def get_extra_synthesis_hooks(self) -> List[HammerToolHookAction]:
        extra_hooks = [
            # Only for CVA6
            HammerTool.make_pre_insertion_hook("optimize_design", dont_touch_srams),
            HammerTool.make_post_insertion_hook("configure_dft", insert_internal_memory_collar)
        ]
        return extra_hooks

    def get_extra_atpg_hooks(self) -> List[HammerToolHookAction]:
        extra_hooks = [
            # Only for CVA6
            HammerTool.make_pre_insertion_hook("run_atpg", insert_atpg_memory_collar)
        ]
        return extra_hooks

if __name__ == '__main__':
    ExampleDriver().main()
