#!/usr/bin/env python3
#
# NOTE: this ExampleDriver works for asap7 and nangate45. the custom hooks are
# only used for asap7 though.

import os

from hammer.vlsi import CLIDriver, HammerTool, HammerToolHookAction

from typing import Dict, Callable, Optional, List

def dont_touch_srams(x: HammerTool) -> bool:
    x.append("foreach_in_collection ram [get_references -hierarchical \"*tc_sram_wrapper*\"] {")
    x.append("set_attribute $ram is_memory_cell true")
    x.append("set_attribute $ram is_physical_black_box true" )
    x.append("set_dont_touch $ram")
    x.append("set_attribute $ram is_black_box true")
    x.append("}")

    x.append("foreach_in_collection ram [get_references -hierarchical \"*tc_sram_wrapper_cache_techno*\"] {")
    x.append("set_attribute $ram is_memory_cell true")
    x.append("set_attribute $ram is_physical_black_box true" )
    x.append("set_dont_touch $ram")
    x.append("set_attribute $ram is_black_box true")
    x.append("}")
    return True

class ExampleDriver(CLIDriver):
    def get_extra_synthesis_hooks(self) -> List[HammerToolHookAction]:
        extra_hooks = [
            # Only for CVA6
            HammerTool.make_pre_insertion_hook("optimize_design", dont_touch_srams)
        ]
        return extra_hooks

if __name__ == '__main__':
    ExampleDriver().main()
